// Script to create index.ts for Prisma generated client
// Run after prisma generate to provide unified import path

import { writeFileSync, existsSync } from "fs";
import { join } from "path";

const outputDir = join(process.cwd(), "src/generated/prisma");
const indexPath = join(outputDir, "index.ts");

// Only create if output directory exists (prisma generate was successful)
if (existsSync(outputDir)) {
  const content = `// Re-export all from Prisma generated files
// Auto-generated by scripts/prisma-postgenerate.ts

export * from "./client";
export * from "./enums";
export * from "./models";
`;

  writeFileSync(indexPath, content);
  console.log("Created src/generated/prisma/index.ts");
}
